### ISSUE TITLE
[FEATURE]适配消息平台 Lagrange

### ISSUE THREAD

**Issue by 8ebb82** [AmethystTim/JM_PDF_plugin#33]
目前在 Lagrange 平台上 bot 在正常地完成下载和拼接之后，没有发送 pdf 文件。

source:#32 

[refer link](https://github.com/AmethystTim/JM_PDF_plugin/issues/32#issuecomment-2868959022)

**Comment by AmethystTim** [comment]
如果使用lagrange消息平台的话

是可以直接**在群聊中**使用插件的，但目前bot似乎无法在**私聊中上传文件**

请检查一下你说的“没有发送pdf文件”是否是在私聊中进行的

> 可能是langrange消息平台的问题，总之~~推荐使用NapCat消息平台~~

**Comment by 8ebb82** [comment]
目前看来是这样的，但是 bot 还是无法发送文件。

在群聊中，bot 在正常地下载、拼接完毕后，会提示`文件发送完成，20s后自动撤回`，但是并没有发送文件。20s 后查看控制台日志，提示文件不存在，撤回失败：

```log
langbot  | [JM PDF plugin] 文件xxxxxx-1.pdf不存在，撤回失败
```

在私聊中，bot 则只是下载和拼接文件，没有提示文件发送，也没有真正地发送文件。

---

ps：我把 lagrange 的 http 服务的端口改到了 45678，JM PDF plugin 中的 main.py 的端口也改成了 45678

```py
self.msg_platform = MsgPlatform("host.docker.internal", 45678)
```

```yaml
{
    "Type": "Http",
    "Host": "127.0.0.1",
    "Port": 45678,
    "AccessToken": ""
}
```

**Comment by AmethystTim** [comment]
如果你是通过docker部署的langbot，可以试着检查一下`config.yml`文件里面的`base_dir`项

issue [#9](https://github.com/AmethystTim/JM_PDF_plugin/issues/9#issuecomment-2754889346) 可能对你有帮助

**Comment by 8ebb82** [comment]
这个问题之前遇到过，路径映射错误导致漫画无法下载。我已经正确配置了路径映射，漫画是可以正常下载到本地的。

langbot 的 `docker-compose.yaml`：

```yaml
services:
    ...
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
```

插件的 `config.yaml`：

```yaml
dir_rule:
  base_dir: "/app/plugins/jm-downloads"
```

这样，docker 中 /app 映射的就是本机的 langbot 的根目录，所以下载路径是 `本机 langbot 根路径/plugins/jm-downloads`，经过实际测试确实是。

是否需要我提供 lagrange 的详细日志（Trace 级别）？这里有一个[lagrange 的相关 issue](https://github.com/LagrangeDev/Lagrange.Core/issues/793#issue-2947007016)，我想不是插件的问题吧。不过 issue 主说只有私聊中不行......
