### ISSUE TITLE
[HELP] Bot可以响应jm下载命令，也转成了pdf，但是没有上传操作

### ISSUE THREAD

**Issue by SquirrelEdison** [AmethystTim/JM_PDF_plugin#35]
- [x] 是否按照README描述步骤进行安装？
- [x] 是否已查看README常见问题进行过问题排查？
- [x] 是否确保`jmcomic`为最新版本？
2.5.39，为最新版本
- [x] 是否确保消息平台为最新版本？
拉取的latest镜像，是最新版本

### 问题描述（出现的问题）
服务器可以下载本子图片，但是下载后没有任何反应了，日志也没有显示。测试时发现`/jm (help)`命令也无效，只能响应`/jm [ID] [chapter]`命令

![Image](https://github.com/user-attachments/assets/981bfa34-4f33-45ce-98d7-d1db593cbbf1)

### 期望效果（你的预期效果是什么）
能够将下载好的图片转成pdf并发出来

### 复现步骤（描述出现问题时的操作步骤）
在群聊发送`/jm [ID]`后，Bot提示正在下载，但是后续没有任何反应

### 报错日志（langbot与消息平台日志）
`langbot`日志：
![Image](https://github.com/user-attachments/assets/bb6bfccb-9794-4766-8205-188f00fa1573)
上图可以看到下载已经完成

![Image](https://github.com/user-attachments/assets/f300f96b-9b89-4ad8-a790-dfacda64b06c)
并且能够看到下载好的`.jpg`，经查看这些jpg都是成功下载好的，无异常。

`napcat`日志：
![Image](https://github.com/user-attachments/assets/8a8c2cd5-c8fd-4a13-85be-056d99c790e4)
上述就是最后的日志了，后续没有更新的日志了

### 设备信息（操作系统、LangBot部署方式、消息平台名称及部署方式）
操作系统：ubuntu 22.04 LTS
LangBot部署方式：docker
NapCat部署方式：docker

**Comment by SquirrelEdison** [comment]
补充，刚刚再次调用发现pdf转化成功了，但是无法发送出来，怀疑tx检测到pdf内容敏感后直接发不出来了，而且号还被限制了
`langbot`日志见下图左边，文件浏览在右边
<img width="1430" alt="Image" src="https://github.com/user-attachments/assets/6af37d3c-7c57-4c62-8bde-c69a42afaea0" />


<img width="360" alt="Image" src="https://github.com/user-attachments/assets/34e51128-6612-4a44-91fd-b39e1bc5e389" />
仍然是发不出来。怀疑可能是最近qq变严格了许多，我个人的浅薄建议：可以考虑加一个压缩功能，把pdf压缩加密码后再发。

**Comment by AmethystTim** [comment]
如果方便附一下config.yml与docker.yml配置

然后截图一下NapCat的网络配置

**Comment by SquirrelEdison** [comment]
`NapCat网络配置`
![Image](https://github.com/user-attachments/assets/3b9b894a-3f2f-45d1-9eba-16c0cb280c0a)

`docker.yml`
```yml
################################################
# 特别注意：                            
# 如果你是使用Docker部署LangBot的用户，请按照以下步骤修改配置文件：
# 修改docker_cfg配置项
# - 将enabeld设置为true
# - 将host_base_dir修改为宿主机上PDF的实际存储目录
#
# 例如: "C:\\Users\\Hello\\Desktop\\downloads"
################################################

docker_cfg: # 非Docker部署LangBot用户请无视此项
  enabled: true # 是否使用Docker部署LangBot
  host_base_dir: "/app/plugins/JM-PDF-plugin/downloads/" # 宿主机上PDF的实际存储目录（注意转义字符的使用）

```

`config.yml`
```yml
# Github Actions 下载脚本配置
version: '2.0'

################################################
# 特别注意：                            
# 如果你是使用Docker部署LangBot的用户，请按照以下步骤修改配置文件：
#
# 将dir_rule中的base_dir一项修改为LangBot容器内的可达路径
#
# 根据LangBot的挂载配置，你目前可以在这两个目录下选择你想存储PDF的位置
#    - /app/data
#    - /app/plugins 
#
# 例如："/app/plugins/JM_PDF_plugin/downloads/"
################################################

dir_rule:
  base_dir: "/app/plugins/JM-PDF-plugin/downloads/" # 漫画/PDF的存储目录（注意转义字符的使用）
  rule: Bd_Aid_Pindex

# 域名配置，若均无法访问可尝试用“#”注释client所有部分，以使用默认配置的域名列表
client:
  impl: api
  domain:
    api:
      - www.cdnmhws.cc
      - www.cdnuc.vip
      - www.cdnmhwscc.vip
      - www.cdnblackmyth.club

# 下载配置，无需关注
download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    batch_count: 45

# jmcomic包插件项配置，非必需配置
plugins:
  after_init:
    - plugin: login # 登录插件，以下载某些需要登录才能下载的漫画，需要配置登录信息
      kwargs:
        username: usernamex # 用户名
        password: 1919810d # 密码
```

**Comment by AmethystTim** [comment]
嗯今天复现了一下你的问题，情况比较复杂（）

## 概述

首先是**消息平台部署在docker中**的这种情况，我在设计插件的时候没有考虑到

目前为止插件是支持以下两种部署方法

1. 主机部署langbot+主机部署消息平台
2. docker部署langbot+主机部署消息平台

## 下载成功后没有发出pdf的原因

简单概括是因为消息平台（napcat）会根据你在`docker.yml`中填写的路径`host_base_dir`来寻找相应的pdf文件，如果消息平台在主机上那么是没有问题的。

但是由于你的消息平台部署在docker中，napcat只能在容器中的的文件系统中寻找这个pdf，所以肯定是找不到的。

---

## 临时解决方案

1. 修改napcat-docker的`docker-compose.yml`，**添加一个挂载配置**，比如

```yaml
volumes:
    - ../../LangBot/plugins/JM-PDF-plugin/downloads:/app/downloads
```

2. 修改`docker.yml`中的`host_base_dir`，改为**消息平台容器**内的**挂载的存储目录的路径**

```yaml
host_base_dir: "/app/downloads"
```

---

## 完整配置文件供参考

- napcat-docker的`docker-compose.yml`

```yaml
services:
    napcat:
        environment:
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        networks:
            - langbot-network
        ports:
            - 3000:3000
            - 3001:3001
            - 6099:6099
        volumes:
            - ../../LangBot/plugins/JM-PDF-plugin/downloads:/app/downloads
        container_name: napcat
        restart: always
        image: mlikiowa/napcat-docker:latest

networks:
  langbot-network:
    external: true
```

- 插件的`docker.yml`

```yaml
################################################
# 特别注意：                            
# 如果你是使用Docker部署LangBot的用户，请按照以下步骤修改配置文件：
# 修改docker_cfg配置项
# - 将enabeld设置为true
# - 将host_base_dir修改为宿主机上PDF的实际存储目录
#
# 例如: "C:\\Users\\Hello\\Desktop\\downloads"
################################################

docker_cfg: # 非Docker部署LangBot用户请无视此项
  enabled: true # 是否使用Docker部署LangBot
  host_base_dir: "/app/downloads" # 宿主机上PDF的实际存储目录（注意转义字符的使用）
```

**Comment by SquirrelEdison** [comment]
抱歉，我一开始没有理解您的意思，我以为是langbot的docker-compose.yml
我刚刚按照您说的修改了，但还是无法上传文件：
这是修改后的langbot报错日志
![Image](https://github.com/user-attachments/assets/fec7d474-52dd-44ac-ab19-f658b6f4dad6)

这是napcat的日志
![Image](https://github.com/user-attachments/assets/a9e99546-de86-4ef9-ae17-ef816c2fb950)

napcat的网络配置
![Image](https://github.com/user-attachments/assets/7dc41c4f-928d-4645-a515-4c4c4a7cf0f0)

这是修改后的napcat docker-compose.yaml
```yaml
# docker-compose.yaml
# version: "3"
services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    ports:
      - 3000:3000
      - 3001:3001
      - 6099:6099
    volumes:
      - ../LangBot/plugins/JM-PDF-plugin/downloads:/app/downloads   # 因为我的LangBot和NapCat只差一级目录
    restart: always
    networks:
      - langbot-network

networks:
  langbot-network:
    external: true
```

tree命令：
```
.
├── LangBot
│   ├── components.yaml
│   ├── CONTRIBUTING.md
│   ├── data
│   ├── docker-compose.yaml
│   ├── Dockerfile
│   ├── libs
│   ├── LICENSE
│   ├── main.py
│   ├── pkg
│   ├── plugins
│   ├── pyproject.toml
│   ├── README_EN.md
│   ├── README_JP.md
│   ├── README.md
│   ├── res
│   ├── templates
│   └── web
└── NapCat
    ├── docker-compose.yaml
    ├── NapCat-Docker
    └── napcat.sh

10 directories, 12 files
```


这是langbot docker-compose.yaml
```yaml
# version: "3"

services:
  langbot:
    image: rockchin/langbot:latest
    container_name: langbot
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    networks:
      - langbot-network
    ports:
      - 5300:5300  # 供 WebUI 使用
      - 2280-2290:2280-2290  # 供消息平台适配器方向连接
    # 根据具体环境配置网络
networks:
  langbot-network:
    external: true
```

这是插件的docker.yml
```yml
################################################
# 特别注意：                            
# 如果你是使用Docker部署LangBot的用户，请按照以下步骤修改配置文件：
# 修改docker_cfg配置项
# - 将enabeld设置为true
# - 将host_base_dir修改为宿主机上PDF的实际存储目录
#
# 例如: "C:\\Users\\Hello\\Desktop\\downloads"
################################################

docker_cfg: # 非Docker部署LangBot用户请无视此项
  enabled: true # 是否使用Docker部署LangBot
  host_base_dir: "/app/downloads" # 宿主机上PDF的实际存储目录（注意转义字符的使用）
```
